import { IssuedCertificate, StudentDetails } from './types';

export const dummyStudentData: Record<string, StudentDetails> = {
  "12345": {
    fullName: "John Doe",
    fatherName: "Michael Doe",
    motherName: "Sarah Doe",
    nationality: "American",
    category: "General",
    dateOfBirth: "2005-05-15",
    dateOfAdmission: "2020-06-01",
    class: "10th Grade",
    section: "A",
    admissionNumber: "12345",
    currentClass: "10th Grade",
    admitClass: "9th Grade",
    academicYear: "2023-2024",
    lastAttendanceDate: "2024-03-15",
    lastClass: "10th Grade",
    tcNo: "TC-12345",
    school: "City High School",
    behavior: "Excellent",
    feesUpToDate: "2024-03-15",
    reason: "",
    maxAttendance: "220",
    obtainedAttendance: "210",
    lastExam: "Final Exam",
    whetherFailed: "No",
    tcCharge: "Paid",
    examIn: "School",
    qualified: "Yes",
    toClass: "11th Grade",
    classInWords: "Eleventh",
    conduct: "Good",
    remark: "Good student",
    behaviorRemarks: "Exemplary behavior",
    subjectStudied: "Math, Science",
    gamesPlayed: "Football",
    extraActivity: "Music",
    rollNo: "123",
    dateOfLeaving: "2024-03-15",
    dateOfIssue: "2024-03-18",
    remarks: "None"
  },
  "67890": {
    fullName: "Jane Smith",
    fatherName: "Robert Smith",
    motherName: "Mary Smith",
    nationality: "British",
    category: "SC",
    dateOfBirth: "2006-08-22",
    dateOfAdmission: "2021-06-01",
    class: "9th Grade",
    section: "A",
    admissionNumber: "67890",
    currentClass: "9th Grade",
    admitClass: "8th Grade",
    academicYear: "2023-2024",
    lastAttendanceDate: "2024-03-15",
    lastClass: "9th Grade",
    tcNo: "TC-67890",
    school: "Town High School",
    behavior: "Good",
    feesUpToDate: "2024-02-28",
    reason: "",
    maxAttendance: "220",
    obtainedAttendance: "210",
    lastExam: "Midterm Exam",
    whetherFailed: "No",
    tcCharge: "Unpaid",
    examIn: "Private",
    qualified: "No",
    toClass: "10th Grade",
    classInWords: "Tenth",
    conduct: "Satisfactory",
    remark: "Needs improvement",
    behaviorRemarks: "Generally well-behaved",
    subjectStudied: "English, History",
    gamesPlayed: "Basketball",
    extraActivity: "Drama",
    rollNo: "456",
    dateOfLeaving: "2024-03-15",
    dateOfIssue: "2024-03-18",
    remarks: "None"
  }
};

export const dummyIssuedCertificates: IssuedCertificate[] = [
  {
    studentName: "John Doe",
    studentClass: "10th Grade",
    admissionNumber: "12345",
    motherName: "Sarah Doe",
    fatherName: "Michael Doe",
    nationality: "American",
    category: "General",
    dateOfBirth: "2005-05-15",
    lastClass: "10th Grade",
    issueDate: "2024-03-10",
    dateOfLeaving: "2024-03-15",
    reason: "Family relocation",
    examIn: "School",
    qualified: "Yes",
    gamesPlayed: "Football",
    extraActivity: "Music",
    tcNo: "520",
    subject: "Math, Science",
    generalConduct: "Good",
    remarks: "None",
    maxAttendance: "220",
    obtainedAttendance: "210",
    tcCharge: "Paid",
    dateOfIssue: "2024-03-10",
    toClass: "11th Grade",
    classInWords: "Eleventh",
    lastAttendanceDate: "2024-03-15",
    behaviorRemarks: "Exemplary behavior",
    rollNo: "123",
    dateOfIssue: "2024-03-18",
    remarks: "None"
  },
  {
    studentName: "Jane Smith",
    studentClass: "9th Grade",
    admissionNumber: "67890",
    motherName: "Mary Smith",
    fatherName: "Robert Smith",
    nationality: "British",
    category: "SC",
    dateOfBirth: "2006-08-22",
    lastClass: "9th Grade",
    issueDate: "2024-03-12",
    dateOfLeaving: "2024-03-15",
    reason: "Change of residence",
    examIn: "Private",
    qualified: "No",
    gamesPlayed: "Basketball",
    extraActivity: "Drama",
    tcNo: "234",
    subject: "English, History",
    generalConduct: "Satisfactory",
    remarks: "None",
    maxAttendance: "220",
    obtainedAttendance: "210",
    tcCharge: "Unpaid",
    dateOfIssue: "2024-03-12",
    toClass: "10th Grade",
    classInWords: "Tenth",
    lastAttendanceDate: "2024-03-15",
    behaviorRemarks: "Generally well-behaved",
    rollNo: "456",
    dateOfIssue: "2024-03-18",
    remarks: "None"
  }
];