-- CreateTable
CREATE TABLE `Registration` (
    `registrationId` VARCHAR(191) NOT NULL,
    `firstName` VARCHAR(191) NOT NULL,
    `lastName` VARCHAR(191) NOT NULL,
    `gender` VARCHAR(191) NOT NULL,
    `formNo` VARCHAR(191) NOT NULL,
    `dob` VARCHAR(191) NOT NULL,
    `category` VARCHAR(191) NOT NULL,
    `religion` VARCHAR(191) NOT NULL,
    `registerForClass` VARCHAR(191) NOT NULL,
    `admissionCategory` VARCHAR(191) NOT NULL,
    `bloodGroup` VARCHAR(191) NOT NULL,
    `regnDate` VARCHAR(191) NOT NULL,
    `testDate` VARCHAR(191) NOT NULL,
    `transactionNo` VARCHAR(191) NOT NULL,
    `singleParent` BOOLEAN NOT NULL,
    `contactNo` VARCHAR(191) NOT NULL,
    `studentEmail` VARCHAR(191) NOT NULL,
    `address` VARCHAR(191) NOT NULL,
    `city` VARCHAR(191) NOT NULL,
    `state` VARCHAR(191) NOT NULL,
    `pincode` VARCHAR(191) NOT NULL,
    `studentAadharCardNo` VARCHAR(191) NOT NULL,
    `regnCharge` VARCHAR(191) NOT NULL,
    `examSubject` VARCHAR(191) NOT NULL,
    `paymentStatus` VARCHAR(191) NOT NULL,
    `fatherName` VARCHAR(191) NOT NULL,
    `fatherMobileNo` VARCHAR(191) NOT NULL,
    `smsAlert` BOOLEAN NOT NULL,
    `fatherEmail` VARCHAR(191) NOT NULL,
    `fatherAadharCardNo` VARCHAR(191) NOT NULL,
    `isFatherCampusEmployee` BOOLEAN NOT NULL,
    `motherName` VARCHAR(191) NOT NULL,
    `motherMobileNo` VARCHAR(191) NOT NULL,
    `motherAadharCardNo` VARCHAR(191) NOT NULL,
    `casteCertificate` VARCHAR(191) NULL,
    `studentAadharCard` VARCHAR(191) NULL,
    `fatherAadharCard` VARCHAR(191) NULL,
    `motherAadharCard` VARCHAR(191) NULL,
    `previousClassMarksheet` VARCHAR(191) NULL,
    `transferCertificate` VARCHAR(191) NULL,
    `studentDateOfBirthCertificate` VARCHAR(191) NULL,
    `schoolId` INTEGER NULL,

    UNIQUE INDEX `Registration_formNo_key`(`formNo`),
    PRIMARY KEY (`registrationId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Registration` ADD CONSTRAINT `Registration_schoolId_fkey` FOREIGN KEY (`schoolId`) REFERENCES `School`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
